[package]
name = "data-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom_locate = "4.2.0"
rand = "0.8.5"
uuid = { version = "1.5.0", features = ["v4"] }